### ISSUE TITLE
Désactiver un zone temporairement

### ISSUE THREAD

**Issue by lolo1878** [NextDom/plugin-husqvarna#19]
Bonjour,

Est-il possible de pouvoir désactiver / activer une zone en modifiant le pourcentage de passage ?
Merci

**Comment by guenneguezt** [comment]
bonjour
non mais je ne pense pas que l'API officieuse le permet.
Maintenant une API est proposé par husqvarna.
Il faudra refaire un jour le plugin...

**Comment by lolo1878** [comment]
Merci pour ton retour.
Malheureusement, je n'ai toujours rien compris aux API.
